services:
  backend:
    build: .
    container_name: ProcurementBackend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@192.168.110.204:5432/Backend
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
